[package]
name = "felix-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
serenity = { version = "0.12", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
time = { version = "0.3.31", features = ["local-offset", "macros"]}
tokio = { version = "1.34", features = ["macros", "rt-multi-thread"] }
