[package]
name = "felix-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.23"
rusqlite = { version = "0.30.0", features = ["bundled"] }
time = { version = "0.3.31", features = ["macros", "formatting"] }
tokio = { version = "1.34", features = ["macros", "rt-multi-thread"] }
