[build]
# Use pre-built Docker images for cross compilation
# This speeds up the build process significantly
pre-built = true

[target.aarch64-unknown-linux-gnu]
# Use a specific image that's optimized for ARM64 builds
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest"

# Configure environment variables for the build
[target.aarch64-unknown-linux-gnu.env]
# Ensure SQLite is available
PKG_CONFIG_ALLOW_CROSS = "1"
PKG_CONFIG_PATH = "/usr/lib/aarch64-linux-gnu/pkgconfig"
CARGO_BUILD_TARGET = "aarch64-unknown-linux-gnu"

# Optimize build performance
CARGO_PROFILE_RELEASE_LTO = "thin"
CARGO_PROFILE_RELEASE_CODEGEN_UNITS = "1"
CARGO_PROFILE_RELEASE_OPT_LEVEL = "3" 