AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: FelixPearlBot

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - development
    Description: Environment to deploy to

  DiscordWebhookUrl:
    Type: String
    Description: Discord webhook URL for bot messages
    NoEcho: true

  ClaudeApiKey:
    Type: String
    Description: Claude API key for AI message generation
    NoEcho: true

  OpenWeatherApiKey:
    Type: String
    Description: OpenWeather API key for weather data
    NoEcho: true

  BirthdayChannelId:
    Type: String
    Description: Discord channel ID for birthday messages
    Default: ""

  WeatherChannelId:
    Type: String
    Description: Discord channel ID for weather updates
    Default: ""

  NationalDaysChannelId:
    Type: String
    Description: Discord channel ID for national days messages
    Default: ""

  TestMode:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: Enable test mode to suppress messages

Resources:
  FelixPearlBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          DISCORD_WEBHOOK_URL: !Ref DiscordWebhookUrl
          CLAUDE_API_KEY: !Ref ClaudeApiKey
          OPENWEATHER_API_KEY: !Ref OpenWeatherApiKey
          BIRTHDAY_CHANNEL_ID: !Ref BirthdayChannelId
          WEATHER_CHANNEL_ID: !Ref WeatherChannelId
          NATIONAL_DAYS_CHANNEL_ID: !Ref NationalDaysChannelId
          TEST_MODE: !Ref TestMode
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        Project: felix-pearl-bot
        Environment: !Ref Environment
        Service: discord-bot
        CreatedBy: sam
      Events:
        DailyScheduleEDT:
          Type: Schedule
          Properties:
            Schedule: cron(0 11 * * ? *) # 7 AM EDT
            Description: Daily schedule for EDT
            Enabled: true
        DailyScheduleEST:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 * * ? *) # 7 AM EST
            Description: Daily schedule for EST
            Enabled: false

  DSTSwitchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: services.dst_switch.lambda_handler
      Runtime: python3.9
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - events:PutRule
                - events:PutTargets
                - events:DeleteRule
                - events:RemoveTargets
              Resource: "*"
      Events:
        DSTCheck:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 * * ? *)
            Description: Daily DST check
            Enabled: true

Outputs:
  FelixPearlBotFunction:
    Description: Felix & Pearl Bot Lambda Function ARN
    Value: !GetAtt FelixPearlBotFunction.Arn
  DSTSwitchFunction:
    Description: DST Switch Lambda Function ARN
    Value: !GetAtt DSTSwitchFunction.Arn
