AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Felix and Pearl Bot - A Discord bot duo that posts daily messages about national days and weather updates

Resources:
  FelixPearlBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 30
      MemorySize: 128
      Architectures:
        - arm64
      Environment:
        Variables:
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
          FELIX_DISCORD_WEBHOOK_URL: !Ref FelixWebhookUrl
          PEARL_DISCORD_WEBHOOK_URL: !Ref PearlWebhookUrl
          WEATHER_API_KEY: !Ref WeatherApiKey
          WEATHER_LOCATION: !Ref WeatherLocation
          WEATHER_LAT: !Ref WeatherLat
          WEATHER_LON: !Ref WeatherLon
          BIRTHDAYS_CONFIG: !Ref BirthdaysConfig
          TEST_MODE: "false"
          TZ: "America/New_York"
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 7 * * ? *)
            Description: "Trigger Felix and Pearl Bot at 7 AM Eastern Time"
            Enabled: true

Parameters:
  AnthropicApiKey:
    Type: String
    Description: API key for Anthropic's Claude API
    NoEcho: true
  FelixWebhookUrl:
    Type: String
    Description: Discord webhook URL for Felix's messages
    NoEcho: true
  PearlWebhookUrl:
    Type: String
    Description: Discord webhook URL for Pearl's messages
    NoEcho: true
  WeatherApiKey:
    Type: String
    Description: API key for OpenWeather API
    NoEcho: true
  WeatherLocation:
    Type: String
    Description: Location for weather updates
  WeatherLat:
    Type: String
    Description: Latitude for weather updates
  WeatherLon:
    Type: String
    Description: Longitude for weather updates
  BirthdaysConfig:
    Type: String
    Description: JSON string containing birthday data
    NoEcho: true

Outputs:
  FelixPearlBotFunction:
    Description: Felix and Pearl Bot Lambda Function ARN
    Value: !GetAtt FelixPearlBotFunction.Arn 