AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Felix & Pearl Bot - A Discord bot duo that posts daily messages about national days and weather updates

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Architectures:
      - arm64

Resources:
  FelixPearlBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
          FELIX_DISCORD_WEBHOOK_URL: !Ref FelixWebhookUrl
          PEARL_DISCORD_WEBHOOK_URL: !Ref PearlWebhookUrl
          WEATHER_API_KEY: !Ref WeatherApiKey
          WEATHER_LOCATION: !Ref WeatherLocation
          WEATHER_LAT: !Ref WeatherLat
          WEATHER_LON: !Ref WeatherLon
          BIRTHDAYS_CONFIG: !Ref BirthdaysConfig
          TEST_MODE: "false"
          TZ: "America/New_York"
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 7 * * ? *)
            Description: "Trigger Felix & Pearl Bot at 7 AM Eastern Time"
            Enabled: true
      Tags:
        Project: FelixPearlBot
        Environment: Production
        Services: "NationalDays-Weather-Birthdays"

Parameters:
  AnthropicApiKey:
    Type: String
    Description: API key for Anthropic's Claude API (used by both Felix and Pearl)
    NoEcho: true
  WeatherApiKey:
    Type: String
    Description: API key for OpenWeather API (used by Pearl's weather service)
    NoEcho: true
  WeatherLocation:
    Type: String
    Description: Location for weather updates (e.g., "City,State,Country")
    Default: "Merrick,NY,US"
  WeatherLat:
    Type: String
    Description: Latitude for weather updates
    Default: "40.6587"
  WeatherLon:
    Type: String
    Description: Longitude for weather updates
    Default: "-73.5515"
  FelixWebhookUrl:
    Type: String
    Description: Discord webhook URL for Felix's messages
    NoEcho: true
  PearlWebhookUrl:
    Type: String
    Description: Discord webhook URL for Pearl's messages
    NoEcho: true
  BirthdaysConfig:
    Type: String
    Description: JSON string containing birthday data
    Default: "{\"02-16\": {\"name\": \"Thomas\"}, \"11-13\": {\"name\": \"Dylan\"}, \"04-21\": {\"name\": \"Maryann\"}}"
    NoEcho: true

Outputs:
  FelixPearlBotFunction:
    Description: Felix & Pearl Bot Lambda Function ARN
    Value: !GetAtt FelixPearlBotFunction.Arn 