AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Felix-Pearl-Bot-Discord-Weather-Updates

Resources:
  FelixPearlBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src.lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 30
      MemorySize: 128
      Architectures:
        - arm64
      Environment:
        Variables:
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
          FELIX_DISCORD_WEBHOOK_URL: !Ref FelixWebhookUrl
          PEARL_DISCORD_WEBHOOK_URL: !Ref PearlWebhookUrl
          WEATHER_API_KEY: !Ref WeatherApiKey
          WEATHER_LOCATION: !Ref WeatherLocation
          WEATHER_LAT: !Ref WeatherLat
          WEATHER_LON: !Ref WeatherLon
          BIRTHDAYS_CONFIG: !Ref BirthdaysConfig
          TEST_MODE: "false"
          TZ: "America/New_York"
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        project: felix-pearl-bot
        environment: prod
        service: discord-bot
        created-by: sam
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 * * ? *)  # 7/8 AM ET depending on DST
            Description: daily-trigger
            Enabled: true

Parameters:
  AnthropicApiKey:
    Type: String
    Description: anthropic-api-key
    NoEcho: true
  FelixWebhookUrl:
    Type: String
    Description: felix-discord-webhook
    NoEcho: true
  PearlWebhookUrl:
    Type: String
    Description: pearl-discord-webhook
    NoEcho: true
  WeatherApiKey:
    Type: String
    Description: weather-api-key
    NoEcho: true
  WeatherLocation:
    Type: String
    Description: weather-location
  WeatherLat:
    Type: String
    Description: weather-latitude
  WeatherLon:
    Type: String
    Description: weather-longitude
  BirthdaysConfig:
    Type: String
    Description: birthdays-json-config
    NoEcho: true

Outputs:
  FelixPearlBotFunction:
    Description: felix-pearl-bot-lambda-arn
    Value: !GetAtt FelixPearlBotFunction.Arn 