AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Felix-Pearl-Bot-Discord-Weather-Updates

Resources:
  FelixPearlBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src.lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 30
      MemorySize: 128
      Architectures:
        - arm64
      Environment:
        Variables:
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
          FELIX_DISCORD_WEBHOOK_URL: !Ref FelixWebhookUrl
          PEARL_DISCORD_WEBHOOK_URL: !Ref PearlWebhookUrl
          WEATHER_API_KEY: !Ref WeatherApiKey
          WEATHER_LOCATION: !Ref WeatherLocation
          WEATHER_LAT: !Ref WeatherLat
          WEATHER_LON: !Ref WeatherLon
          BIRTHDAYS_CONFIG: !Ref BirthdaysConfig
          TEST_MODE: "false"
          TZ: "America/New_York"
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        project: felix-pearl-bot
        environment: prod
        service: discord-bot
        created-by: sam
      Events:
        DailyScheduleEDT:
          Type: Schedule
          Properties:
            Schedule: cron(0 11 * * ? *)  # 7 AM EDT
            Description: daily-trigger-edt
            Enabled: true
        DailyScheduleEST:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 * * ? *)  # 7 AM EST
            Description: daily-trigger-est
            Enabled: false

  DSTSwitchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src.dst_switch.lambda_handler
      Runtime: python3.12
      Timeout: 30
      MemorySize: 128
      Architectures:
        - arm64
      Environment:
        Variables:
          TZ: "America/New_York"
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - events:PutRule
                - events:PutTargets
                - events:DeleteRule
                - events:RemoveTargets
              Resource: '*'
      Events:
        DSTCheckSchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 8-14 3 ? SUN *)  # Run at midnight on the second Sunday in March
            Description: dst-spring-forward-check
            Enabled: true
        DSTCheckScheduleFallback:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 1-7 11 ? SUN *)  # Run at midnight on the first Sunday in November
            Description: dst-fall-back-check
            Enabled: true

Parameters:
  AnthropicApiKey:
    Type: String
    Description: anthropic-api-key
    NoEcho: true
  FelixWebhookUrl:
    Type: String
    Description: felix-discord-webhook
    NoEcho: true
  PearlWebhookUrl:
    Type: String
    Description: pearl-discord-webhook
    NoEcho: true
  WeatherApiKey:
    Type: String
    Description: weather-api-key
    NoEcho: true
  WeatherLocation:
    Type: String
    Description: weather-location
  WeatherLat:
    Type: String
    Description: weather-latitude
  WeatherLon:
    Type: String
    Description: weather-longitude
  BirthdaysConfig:
    Type: String
    Description: birthdays-json-config
    NoEcho: true

Outputs:
  FelixPearlBotFunction:
    Description: felix-pearl-bot-lambda-arn
    Value: !GetAtt FelixPearlBotFunction.Arn
  DSTSwitchFunction:
    Description: dst-switch-function-arn
    Value: !GetAtt DSTSwitchFunction.Arn 