[build]
# Enable parallel compilation
codegen-units = 16

[profile.release]
# Enable link-time optimization in release mode
lto = "thin"
codegen-units = 1
# Optimize binary size
strip = true  # Strip symbols from binary
opt-level = 3
panic = "abort"  # Remove panic unwinding code 

# Use system allocator for better performance
[target.'cfg(all())']
rustflags = ["-C", "target-cpu=native"]

# Optimize dependencies
[profile.dev.package."*"]
opt-level = 3