name: FelixBot Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      
      - name: Build for Raspberry Pi
        run: cross build --release --target=aarch64-unknown-linux-gnu
      
      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/aarch64-unknown-linux-gnu/release/felix-bot,days.db"
          target: "~"
          fingerprint: ${{ vars.SSH_FINGERPRINT }}
      
      - name: Execute remote commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mv ~/felix-bot /usr/local/bin/felix-bot
            sudo mv ~/days.db /home/tlent/days.db
          fingerprint: ${{ vars.SSH_FINGERPRINT }}
