name: FelixBot Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - uses: actions/checkout@v4

      # Cache Rust dependencies to speed up builds
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "felix-bot-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}"

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest

      # Log in to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Generate a version tag using commit SHA and date
      - name: Generate version tag
        id: version
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "tag=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      # Build and push the Docker image for ARM64
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/felix-bot:latest
            ghcr.io/${{ github.repository_owner }}/felix-bot:${{ steps.version.outputs.date }}-${{ steps.version.outputs.tag }}
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/felix-bot:buildcache
            type=gha
          cache-to: |
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/felix-bot:buildcache,mode=max
            type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            CARGO_NET_GIT_FETCH_WITH_CLI=true

      # Copy days.db and deploy.sh to the server
      - name: Copy days.db and deploy.sh to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          fingerprint: ${{ vars.SSH_FINGERPRINT }}
          source: "days.db,deploy.sh"
          target: "~/felix-bot"

      # Deploy to Raspberry Pi using a script
      - name: Deploy to Raspberry Pi
        id: deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          fingerprint: ${{ vars.SSH_FINGERPRINT }}
          script: |
            chmod +x ~/felix-bot/deploy.sh
            bash ~/felix-bot/deploy.sh ${{ github.repository_owner }} ${{ steps.version.outputs.date }}-${{ steps.version.outputs.tag }}

      # Rollback if deployment fails
      - name: Rollback on failure
        if: failure() && steps.deploy.outcome == 'failure'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          fingerprint: ${{ vars.SSH_FINGERPRINT }}
          script: |
            if [ -f ~/felix-bot/rollback.txt ]; then
              PREVIOUS_IMAGE=$(cat ~/felix-bot/rollback.txt | cut -d' ' -f3)
              if [ "$PREVIOUS_IMAGE" != "none" ]; then
                echo "Rolling back to $PREVIOUS_IMAGE"
                CRON_JOB="0 7 * * * docker run --rm --name felix-bot --env-file ~/felix-bot/.env -v ~/felix-bot/days.db:/app/days.db $PREVIOUS_IMAGE /usr/local/bin/felix-bot >> ~/felix-bot/felix-bot.log 2>&1"
                (crontab -l 2>/dev/null | grep -v "felix-bot"; echo "$CRON_JOB") | crontab -
                echo "Rollback completed"
              fi
            fi